blog/modules/blog/models/CommentForm.php
<?php
/**
 * Created by PhpStorm.
 * User: georgy
 * Date: 14.12.14
 * Time: 0:20
 */

namespace blog\modules\blog\models;


use common\models\Comment;
use Yii;
use yii\base\Model;

class CommentForm extends Model
{
    /**
     * @var null|string action формы
     */
    public $action = null;
    /**
     * @var int|null идентификатор родительского комментария
     */
    public $pid = null;
    /**
     * @var string заголовок комментария
     */
    public $title;
    /**
     * @var string контент комментария
     */
    public $content;

    public function __construct($action = null)
    {
        $this->action = $action;

        parent::__construct();
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pid', 'post_id'], 'integer'],
            [['title', 'content'], 'required'],
            [['title', 'content'], 'string', 'max' => 255]
        ];
    }

    public function attributeLabels()
    {
        return [
            'title' => 'Заголовок',
            'content' => 'Комментарий'
        ];
    }

    /**
     * Сохраняет комментарий.
     * @param Comment $comment модель комментария
     * @param array $data данные пришедшие из формы
     * @return bool
     */
    public function save(Comment $comment, array $data)
    {
        $isLoad = $comment->load([
            'pid' => $data['pid'],
            'title' => $data['title'],
            'content' => $data['content']
        ], '');

        return ($isLoad && $comment->save());
    }
}

blog/modules/blog/controllers/CategoryController.php
<?php

namespace blog\modules\blog\controllers;

use common\models\Category;
use common\models\Tags;
use Yii;
use yii\web\Controller;

class CategoryController extends Controller
{

    public function actionView($id)
    {
        $categoryModel = new Category();
        $category = $categoryModel->getCategory($id);
        $tags = Tags::find()->limit(10)->all();

        $posts = $category->getPosts();

        return $this->render('index', [
            'category' => $category,
            'posts' => $posts,
            'categories' => $categoryModel->getCategories(),
            'tags' => $tags
        ]);
    }
}

blog/modules/blog/controllers/CommentController.php
<?php

namespace blog\modules\blog\controllers;

use common\models\Comment;
use blog\modules\blog\models\CommentForm;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\User;

class CommentController extends Controller
{

    public function actionAdd()
    {
        $model = new Comment();

        $commentForm = new CommentForm(Url::to(['comment/add', 'id' => Yii::$app->request->get('id')]));
        $model->post_id = Yii::$app->request->get('id');

        if (Yii::$app->user instanceof User) {
            $model->author_id = Yii::$app->user->getIdentity()->getId();
        }

        if ($commentForm->save($model, Yii::$app->request->post('CommentForm'))) {
            return $this->redirect(['post/view', 'id' => Yii::$app->request->get('id')]);
        } else {
            return $this->render('create', [
                'model' => $commentForm
            ]);
        }
    }
}

blog/modules/blog/controllers/PostController.php
<?php

namespace blog\modules\blog\controllers;

use common\models\Category;
use common\models\Tags;
use blog\modules\blog\models\CommentForm;
use Yii;
use common\models\Post;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;

class PostController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $post = new Post();
        $category = new Category();
        $tags = Tags::find()->limit(10)->all();
        $posts = $post->getPublishedPosts();

        return $this->render('index', [
            'posts' => $posts,
            'categories' => $category->getCategories(),
            'tags' => $tags
        ]);
    }

    /**
     * @param string $id
     * @return string
     */
    public function actionView($id)
    {
        $post = new Post();
        return $this->render('view', [
            'model' => $post->getPost($id),
            'commentForm' => new CommentForm(Url::to(['comment/add', 'id' => $id])),
        ]);
    }
}

blog/modules/blog/controllers/TagController.php
<?php

namespace blog\modules\blog\controllers;

use common\models\Category;
use common\models\Tags;
use Yii;
use yii\web\Controller;

class TagController extends Controller
{

    /**
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        $tagModel = new Tags();
        $tag = $tagModel->getTag($id);
        $categoryModel = new Category();

        $tags = Tags::find()->limit(10)->all();
        
        $posts = $tag->getPublishedPosts();

        return $this->render('view', [
            'tag' => $tag,
            'tags' => $tags,
            'posts' => $posts,
            'categories' => $categoryModel->getCategories()
        ]);
    }
}

blog/modules/blog/controllers/TagsController.php
<?php

namespace blog\modules\blog\controllers;

use Yii;
use common\models\Tags;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TagsController implements the CRUD actions for Tags model.
 */
class TagsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['admin']
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Tags models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Tags::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tags model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tags model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tags();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Tags model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Tags model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tags model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tags the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tags::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

blog/modules/blog/views/category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

blog/modules/blog/views/category/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = Yii::t('backend', 'Create Category');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

blog/modules/blog/views/category/index.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;

/** @var $this yii\web\View */
/** @var $category \common\models\Category */
/** @var $categories \yii\data\ActiveDataProvider */
/** @var $posts \yii\data\ActiveDataProvider */

?>

<!-- begin content-->
<div class="crm__container">
    <!-- begin aside-->
    <div class="aside">
        <div class="tags">
            <div class="tags__title">Популярное сейчас</div>
            <div class="tags__list">
                <?php
                foreach ($tags as $tag) {
                    echo Html::a($tag->title, ['/blog/tag/view', 'id' => $tag->id], ['class' => 'tags__item']);
                }
                ?>
            </div>
        </div>
        <div class="social__widget_wrap" id="vk_groups"></div>
        <script type="text/javascript" src="//vk.com/js/api/openapi.js?150"> </script>
        <script>VK.Widgets.Group("vk_groups", {mode: 5, width: '270'}, 20003922);</script>
    </div>
    <!-- end aside-->
    <div class="crm__content">
        <div class="tab-menu tab-menu--short tab-menu--single">
            <?php
            foreach ($categories->models as $category) {
                echo $this->render('/category/shortViewCategory', [
                    'model' => $category
                ]);
            }
            ?>
        </div>
        <div class="blog__list">
            <?php
            foreach ($posts->models as $post) {
                echo $this->render('/post/shortView', [
                    'model' => $post
                ]);
            }
            ?>
            <div>
                <?= LinkPager::widget([
                    'pagination' => $posts->getPagination()
                ]) ?>
            </div>
        </div>
    </div>
</div>

blog/modules/blog/views/category/shortViewCategory.php
<?php

/* @var $model common\models\Category */
?>
<div class="tab-menu__label active"><?= \yii\helpers\Html::a($model->title, ['category/view', 'id' => $model->id])?></div>

blog/modules/blog/views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = Yii::t('backend', 'Update Category:') . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="category-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

blog/modules/blog/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('backend', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('backend', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
        ],
    ]) ?>

</div>